import { CountryOption } from '@/types/youtube';

export const COUNTRIES: CountryOption[] = [
  { code: 'KR', name: '대한민국', flag: '🇰🇷' },
  { code: 'US', name: '미국', flag: '🇺🇸' },
  { code: 'JP', name: '일본', flag: '🇯🇵' },
  { code: 'GB', name: '영국', flag: '🇬🇧' },
  { code: 'DE', name: '독일', flag: '🇩🇪' },
  { code: 'FR', name: '프랑스', flag: '🇫🇷' },
  { code: 'CA', name: '캐나다', flag: '🇨🇦' },
  { code: 'AU', name: '호주', flag: '🇦🇺' },
  { code: 'BR', name: '브라질', flag: '🇧🇷' },
  { code: 'IN', name: '인도', flag: '🇮🇳' },
  { code: 'CN', name: '중국', flag: '🇨🇳' },
  { code: 'RU', name: '러시아', flag: '🇷🇺' },
  { code: 'IT', name: '이탈리아', flag: '🇮🇹' },
  { code: 'ES', name: '스페인', flag: '🇪🇸' },
  { code: 'MX', name: '멕시코', flag: '🇲🇽' },
  { code: 'NL', name: '네덜란드', flag: '🇳🇱' },
  { code: 'SE', name: '스웨덴', flag: '🇸🇪' },
  { code: 'NO', name: '노르웨이', flag: '🇳🇴' },
  { code: 'DK', name: '덴마크', flag: '🇩🇰' },
  { code: 'FI', name: '핀란드', flag: '🇫🇮' },
  { code: 'PL', name: '폴란드', flag: '🇵🇱' },
  { code: 'TR', name: '터키', flag: '🇹🇷' },
  { code: 'ZA', name: '남아프리카공화국', flag: '🇿🇦' },
  { code: 'AR', name: '아르헨티나', flag: '🇦🇷' },
  { code: 'CL', name: '칠레', flag: '🇨🇱' },
  { code: 'CO', name: '콜롬비아', flag: '🇨🇴' },
  { code: 'PE', name: '페루', flag: '🇵🇪' },
  { code: 'VE', name: '베네수엘라', flag: '🇻🇪' },
  { code: 'TH', name: '태국', flag: '🇹🇭' },
  { code: 'VN', name: '베트남', flag: '🇻🇳' },
  { code: 'ID', name: '인도네시아', flag: '🇮🇩' },
  { code: 'MY', name: '말레이시아', flag: '🇲🇾' },
  { code: 'SG', name: '싱가포르', flag: '🇸🇬' },
  { code: 'PH', name: '필리핀', flag: '🇵🇭' },
  { code: 'TW', name: '대만', flag: '🇹🇼' },
  { code: 'HK', name: '홍콩', flag: '🇭🇰' },
  { code: 'SA', name: '사우디아라비아', flag: '🇸🇦' },
  { code: 'AE', name: '아랍에미리트', flag: '🇦🇪' },
  { code: 'IL', name: '이스라엘', flag: '🇮🇱' },
  { code: 'EG', name: '이집트', flag: '🇪🇬' },
  { code: 'NG', name: '나이지리아', flag: '🇳🇬' },
  { code: 'KE', name: '케냐', flag: '🇰🇪' },
  { code: 'MA', name: '모로코', flag: '🇲🇦' },
  { code: 'GH', name: '가나', flag: '🇬🇭' },
  { code: 'UG', name: '우간다', flag: '🇺🇬' },
  { code: 'TZ', name: '탄자니아', flag: '🇹🇿' },
  { code: 'ZW', name: '짐바브웨', flag: '🇿🇼' },
  { code: 'LK', name: '스리랑카', flag: '🇱🇰' },
  { code: 'BD', name: '방글라데시', flag: '🇧🇩' },
  { code: 'PK', name: '파키스탄', flag: '🇵🇰' },
  { code: 'NP', name: '네팔', flag: '🇳🇵' }
];

export const DEFAULT_COUNTRY = 'KR';